owner: monzim # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository


sites:
  - name: Portfolio
    url: https://monzim.com
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: VPD Calculator
    url: https://vpd.monzim.com
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: OpenChat
    url: https://openchat.monzim.com
  - name: OpenChat API
    url: https://openchat-uriepmo.monzim.com
  - name: kepathalo
    url: https://kepathalo.monzim.com
  - name: niu-analytics
    url: https://niu-analytics.monzim.com
  - name: SongKhep
    url: https://songkhep.monzim.com
  - name: Aurora Docs
    url: https://docs.aurora.monzim.com

status-website:
  baseUrl: /upptime
  logoUrl: https://storage-portfolio.monzim.com/monzim-logo.svg
  name: Uptime
  introTitle: "**Uptime** Status of services"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
