owner: monzim 
repo: upptime 

sites:
  - name: Portfolio
    url: https://monzim.com
    expectedStatusCodes:
      - 200
      - 201
      - 403

  - name: VPD Calculator
    url: https://vpd.monzim.com
    expectedStatusCodes:
      - 200
      - 201
      - 403

  - name: OpenChat
    url: https://openchat.monzim.com
  - name: OpenChat API
    url: https://openchat-uriepmo.monzim.com
    expectedStatusCodes:
      - 200
      - 201
      - 403

  - name: UIU EduQueue
    url: https://eduqueue.monzim.com

  - name: UIU EduQueue Api
    url: https://kash_meranaseb_itna_mehrbanhota-kizarapehle_mulaqat_hojati_unse.monzim.com/api/health
    method: GET
    expectedStatusCodes:
      - 200
      - 403

  - name: kepathalo
    url: https://kepathalo.monzim.com
  - name: niu-analytics
    url: https://niu-analytics.monzim.com
    expectedStatusCodes:
      - 200
      - 201
      - 403

  - name: SongKhep
    url: https://songkhep.monzim.com
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Aurora Docs
    url: https://docs.aurora.monzim.com

  - name: UCAM Protector Chrome Extension
    url: $UCAM_PROTECTOR_PING
    headers:
      - "x-appwrite-project: $UCAM_PROTECTOR_PROJECT_ID"
      - "Content-Type: application/json"
    expectedStatusCodes:
      - 200

status-website:
  theme: light
  baseUrl: /upptime
  logoUrl: https://storage-portfolio.monzim.com/monzim-logo.svg
  name: Monzim - Uptime
  introTitle: "**Uptime** of Services from Monzim"
  introMessage:
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
